shell:
  program: /usr/bin/fish
  args:
    - --login
    - --command
    - "tmux attach || tmux"
env:
  TERM: alacritty
colors: # Nord color scheme
  primary:
    background: '#2E3440'
    foreground: '#D8DEE9'
  normal:
    black:   '#3B4252'
    red:     '#BF616A'
    green:   '#A3BE8C'
    yellow:  '#EBCB8B'
    blue:    '#81A1C1'
    magenta: '#B48EAD'
    cyan:    '#88C0D0'
    white:   '#E5E9F0'
  bright:
    black:   '#4C566A'
    red:     '#BF616A'
    green:   '#A3BE8C'
    yellow:  '#EBCB8B'
    blue:    '#81A1C1'
    magenta: '#B48EAD'
    cyan:    '#8FBCBB'
    white:   '#ECEFF4'
font:
  size: 14
  normal:
    family: 'Hack'
    style: Regular
  bold:
    family: 'Hack'
    style: Bold
  italic:
    family: 'Hack'
    style: Italic
  bold_italic:
    family: 'Hack'
    style: Bold Italic
background_opacity: 0.9
