shell:
  program: /usr/bin/fish
  args:
    - --login
    - --command
    - "tmux attach || tmux"
env:
  TERM: alacritty
colors: # material ocean
  primary:
    background: '0x0f111a'
    foreground: '0xD8DEE9'
  cursor:
    cursor: '0xff4151'
  normal:
    black:      '0x4C566A'
    red:        '0xBF616A'
    green:      '0xA3BE8C'
    yellow:     '0xEBCB8B'
    blue:       '0x81A1C1'
    magenta:    '0xB48EAD'
    cyan:       '0x88C0D0'
    white:      '0xE5E9F0'
font:
  size: 14
  normal:
    family: 'Hack Nerd Font Mono'
    style: Regular
  bold:
    family: 'Hack Nerd Font Mono'
    style: Bold
  italic:
    family: 'Hack Nerd Font Mono'
    style: Italic
  bold_italic:
    family: 'Hack Nerd Font Mono'
    style: Bold Italic
window:
  decorations: none
background_opacity: 0.95
