[[plugins]]
  repo = 'Raimondi/delimitMate'
  on_i = 1

[[plugins]]
  repo = 'kana/vim-smartinput'
  on_i = 1

[[plugins]]
  repo = 'ekalinin/Dockerfile.vim'
  on_ft = ['dockerfile']

[[plugins]]
  repo = 'mustache/vim-mustache-handlebars'
  on_ft = ['handlebars']

[[plugins]]
  repo = 'wavded/vim-stylus'
  on_ft = ['vue', 'stylus']

[[plugins]]
  repo = 'posva/vim-vue'
  on_ft = ['vue']

[[plugins]]
  repo = 'jelera/vim-javascript-syntax'
  on_ft = ['vue', 'javascript']

[[plugins]]
  repo = 'cespare/vim-toml'
  on_ft = ['toml']

[[plugins]]
  repo = 'fatih/vim-go'
  on_ft = ['go']
  source = '~/.config/nvim/confs/plugins/vim-go.vim'

[[plugins]]
  repo = 'zchee/deoplete-go'
  build = 'make'
  on_ft = ['go']
  source = '~/.config/nvim/confs/plugins/deoplete-go.vim'

[[plugins]]
  repo = 'OmniSharp/omnisharp-vim'
  on_ft = ['cs', 'csi', 'csx']
  source = '~/.config/nvim/confs/plugins/omnisharp-vim.vim'

[[plugins]]
  repo = 'zchee/deoplete-clang'
  on_ft = ['c', 'cpp']
  source = '~/.config/nvim/confs/plugins/deoplete-clang.vim'

[[plugins]]
  repo = 'm2mdas/phpcomplete-extended'
  on_ft = ['php']
  source = '~/.config/nvim/confs/plugins/phpcomplete-extended.vim'

[[plugins]]
  repo = 'dag/vim-fish'
  on_ft = ['fish']

[[plugins]]
  repo = 'zchee/deoplete-jedi'
  on_ft = ['python']
