[[plugins]]
  repo = 'Shougo/deol.nvim'

[[plugins]]
  repo = 'Shougo/neosnippet.vim'

[[plugins]]
  repo = 'Shougo/neosnippet-snippets'

[[plugins]]
  repo = 'honza/vim-snippets'

[[plugins]]
  repo = 'cocopon/iceberg.vim'

[[plugins]]
  repo = 'Shougo/deoplete.nvim'

[[plugins]]
  repo = 'Shougo/neomru.vim'

[[plugins]]
  repo = 'Shougo/neoyank.vim'

[[plugins]]
  repo = 'kmnk/vim-unite-giti.git'

[[plugins]]
  repo = 'Shougo/vinarise'

[[plugins]]
  repo = 'nathanaelkane/vim-indent-guides'

[[plugins]]
  repo = 'fatih/vim-go'

[[plugins]]
  repo = 'tyru/caw.vim'

[[plugins]]
  repo = 'itchyny/lightline.vim'

[[plugins]]
  repo = 'Shougo/vimfiler.vim'

[[plugins]]
  repo = 'tpope/vim-dispatch'

[[plugins]]
  repo = 'Shougo/denite.nvim'

[[plugins]]
  repo = 'Shougo/unite.vim'

[[plugins]]
  repo = 'neomake/neomake'
